function T = ImportClassListSpreadsheetNames(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  T = ImportClassListSpreadsheetNames(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  T = ImportClassListSpreadsheetNames(FILE, SHEET) reads from the specified
%  worksheet.
%
%  T = ImportClassListSpreadsheetNames(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  classlistae50125 = importfile("C:\Users\chris\OneDrive\Documents\teaching\ae501_25\class_list_ae501_25.xlsx", "ae501_23", [2, 72]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Oct-2025 19:55:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 72];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
% opts.DataRange = "A" + dataLines(1, 1) + ":A" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = "Name";
opts.VariableTypes = "string";

% Specify variable properties
opts = setvaropts(opts, "Name", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Name", "EmptyFieldRule", "auto");

% Import the data
T = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":A" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    T = [T; tb]; %#ok<AGROW>
end

end