function T = ImportClassListSpreadsheetNamesAndYouTubeCommentSubstring(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  T = ImportClassListSpreadsheetNamesAndYouTubeCommentSubstring(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  T = ImportClassListSpreadsheetNamesAndYouTubeCommentSubstring(FILE, SHEET) reads from the specified
%  worksheet.
%
%  T = ImportClassListSpreadsheetNamesAndYouTubeCommentSubstring(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  classlistae50125 = importfile("C:\Users\chris\OneDrive\Documents\teaching\ae501_25\class_list_ae501_25.xlsx", "ae501_23", [1, 144]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Oct-2025 20:50:15

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 72];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
% opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Name", "ID", "SISUserID", "YouTubeCommentSubstring"];
opts.VariableTypes = ["string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Name", "ID", "SISUserID", "YouTubeCommentSubstring"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "ID", "SISUserID", "YouTubeCommentSubstring"], "EmptyFieldRule", "auto");

% Import the data
T = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    T = [T; tb]; %#ok<AGROW>
end

%CL: Remove the first row
T = T(2:end,:);

%CL: The first row may have added an extraneous category.  Remove unused
%categories
tableManip = tableManipulator(T);
T = tableManip.RemoveUnusedCategories();

end