function T = ImportYouTubeCommentsDatabaseSpreadsheet(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  T = ImportYouTubeCommentsDatabaseSpreadsheet(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  T = ImportYouTubeCommentsDatabaseSpreadsheet(FILE, SHEET) reads from the
%  specified worksheet.
%
%  T = ImportYouTubeCommentsDatabaseSpreadsheet(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CommentsDownloadTest03 = importfile("C:\GitHub\PythonApplications\Apps\YouTubeCommentDownloader\CommentsDownloadTest03.xlsx", "Sheet1", [2, 4]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Oct-2025 07:15:05

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
% opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Timestamp", "Username", "VideoID", "Comment"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "string"];

% Specify variable properties
opts = setvaropts(opts, "Comment", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Username", "VideoID", "Comment"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Timestamp", "InputFormat", "");

% Import the data
T = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    T = [T; tb]; %#ok<AGROW>
end

end